# In order to ensure that you can run the Django project you will need to provide a Python executable.
# To do so you can inherit from a Python 3.6 image. Review the candidates on Docker Hub and inherite
# from a Debian stretch based image. 

# You can provide an environmental variable that will store the path to your project's working directory.

# You will need to run the "pip install django" command in order to install the necessary dependencies

# Copy the whole contents of this directory on the host to the working directory of the Docker image

# Execute the command pytohn <working-dirctory>/mysite/manage.py runserver 0.0.0.0:8000 to start the 
# Django built-in web server. 
