---
- name: Visual Studio Code installation
  block:
    - name: Download Visual Studio Code repository from AUR
      git:
        repo: https://aur.archlinux.org/visual-studio-code-bin.git
        dest: /home/vagrant/visual-studio-code-bin
    - name: Install Visual Studio Code
      command: makepkg -sri --noconfirm
      args:
        chdir: /home/vagrant/visual-studio-code-bin
      notify: Cleanup vscode
    - name: Install Visual Studio Code extensions
      command: code --install-extension "{{ item }}"
      with_items:
        - ms-python.python
        - ms-azuretools.vscode-docker
        - marcostazi.VS-code-vagrantfile
        - redhat.vscode-yaml
        - PKief.material-icon-theme
        - daylerees.rainglow
    - name: Make sure VSCode User configuration direcory exists
      file:
        path: /home/vagrant/.config/Code/User
        state: directory
    - name: Copy VSCode settings
      copy:
        src: settings.json
        dest: /home/vagrant/.config/Code/User/settings.json
  become: false
...