---
- name: Install Xorg
  pacman:
    name: xorg
    state: latest
  retries: 3
  delay: 3
- name: Install KDE components and fonts
  pacman:
    name: [ plasma-meta, konsole, sddm, ttf-hack, ttf-roboto, adapta-kde, papirus-icon-theme ]
    state: latest
  notify: Post-install kde
- name: KDE customization
  block:
    - name: Make sure .config directory exists
      file:
        path: /home/vagrant/.config
        state: directory
    - name: Make sure KDE config files exist
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - /home/vagrant/.config/plasmarc
        - /home/vagrant/.config/kdeglobals
    - name: Configure KDE
      command: "kwriteconfig5 --file {{ item.0 }} --group {{ item.1 }} --key {{ item.2 }} {{ item.3 }}"
      args:
        chdir: /home/vagrant/.config
      loop:
        - [ "kdeglobals", "General", "desktopFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular" ]
        - [ "kdeglobals", "General", "fixed", "Hack,9,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "General", "font", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "General", "menuFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "General", "smallestReadableFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "General", "taskbarFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "General", "toolBarFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "General", "activeFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "WM", "activeFont", "Roboto,10,-1,5,50,0,0,0,0,0,Regular"]
        - [ "kdeglobals", "Icons", "Theme", "Papirus"]
        - [ "plasmarc", "Wallpapers", "userWallpapers", "/home/vagrant/docker.png"]
        - [ "plasmarc", "Theme", "name", "Adapta"]
  become: false
- name: Make sure SDDM configuration directory exists
  file:
    path: /etc/sddm.conf.d
    state: directory
- name: Copy SDDM configuration
  copy:
    src: sddm-custom.conf
    dest: /etc/sddm.conf.d
...